apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

images:
  - name: ghcr.io/progitas/kube-hello
    newTag: latest

replicas:
  - count: 2
    name: min-app


configMapGenerator:
  - name: app-env
    envs:
      - app.env
