---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: min-app
spec:
  selector:
    matchLabels:
      app: min-app
  replicas: 2
  template:
    metadata:
      labels:
        app: min-app
    spec:
      containers:
        - name: min-app
          image: ghcr.io/progitas/kube-hello
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
          env:
            - name: PUBLIC_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PUBLIC_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: ENVIRONMENT
            - name: PUBLIC_MY_ENV
              value: fix-me
